export default interface IUser {
  id: number,
  company_id?: number,
  email?: string,
  email_verified_at?: string,
  prefix?: string,
  phone?: string,
  phone_verified_at?: string,
  password?: string,
  remember_token?: string,
  reset_token?: string,
  role?: string,
  balance?: number,
  nickname?: string,
  first_name: string,
  last_name?: string,
  patronymic?: string,
  birthdate?: string,
  sex?: string,
  avatar_url?: string,
  is_active: boolean,
  created_at?: string,
  updated_at?: string,
  deleted_at?: string,
}
